nameOverride: ""
fullnameOverride: ""

node:
  id: "public-fullnode"
  network: "testnet"
  chainId: ""

image:
  repository: "ghcr.io/movementlabsxyz/aptos-node"
  tag: "latest"
  pullPolicy: IfNotPresent

dataDir: "/opt/data/aptos"

resources:
  requests:
    cpu: "4"
    memory: "8Gi"
  limits:
    cpu: "8"
    memory: "16Gi"

storage:
  size: "500Gi"
  className: ""
  create: true
  parameters:
    type: "gp3"

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
  ports:
    api: 8080
    p2p: 6182
    metrics: 9101
  enableMetrics: true

serviceAccount:
  create: false
  name: ""
  annotations: {}
  labels: {}

config:
  inline: ""

bootstrap:
  enabled: false
  s3Uri: ""
  region: ""
