base:
  role: "full_node"
  data_dir: "/opt/data"
  waypoint:
    from_file: "/opt/data/genesis/waypoint.txt"

execution:
  genesis_file_location: "/opt/data/genesis/genesis.blob"
  genesis_waypoint:
    from_file: "/opt/data/genesis/genesis_waypoint.txt"

storage:
  rocksdb_configs:
    enable_storage_sharding: false

full_node_networks:
  - network_id: "public"
    discovery_method: "none"
    listen_address: "/ip4/0.0.0.0/tcp/6182"
    seeds:
{{- range .Values.fullnode.seeds }}
      {{ .peerId }}:
        addresses:
{{- range .addresses }}
        - "{{ . }}"
{{- end }}
        role: "Upstream"
{{- end }}

api:
  enabled: true
  address: 0.0.0.0:8080

state_sync:
  state_sync_driver:
    bootstrapping_mode: ApplyTransactionOutputsFromGenesis
    continuous_syncing_mode: ApplyTransactionOutputs
