base:
  role: "full_node"
  data_dir: "/opt/data"
  waypoint:
    from_file: "/opt/data/genesis/waypoint.txt"

randomness_override_seq_num: 999999999

execution:
  genesis_file_location: "/opt/data/genesis/genesis.blob"
  genesis_waypoint:
    from_file: "/opt/data/genesis/genesis_waypoint.txt"

storage:
  rocksdb_configs:
    enable_storage_sharding: false
  storage_pruner_config:
    ledger_pruner_config:
      enable: false

full_node_networks:
- network_id:
    private: "vfn"
  listen_address: "/ip4/0.0.0.0/tcp/6181"
  seeds:
    {{ .Values.vfn.validator.peerId }}:
      addresses:
      - "/dns/{{ .Values.vfn.validator.serviceName }}.{{ .Values.vfn.validator.namespace }}.svc.cluster.local/tcp/{{ .Values.vfn.validator.port }}/noise-ik/{{ .Values.vfn.validator.publicKey }}/handshake/0"
      role: "Validator"
- network_id: "public"
  listen_address: "/ip4/0.0.0.0/tcp/6182"
  identity:
    type: "from_config"
    key: "{{ .Values.vfn.fullnode.publicKey }}"
    peer_id: "{{ .Values.vfn.fullnode.peerId }}"

admin_service:
  enabled: true
  address: 127.0.0.1
  port: 9102

api:
  enabled: true
  address: "0.0.0.0:8080"

state_sync:
  state_sync_driver:
    bootstrapping_mode: ApplyTransactionOutputsFromGenesis
    continuous_syncing_mode: ApplyTransactionOutputs
