{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (include "movement-fullnode.fullname" .) }}
  labels:
{{ include "movement-fullnode.labels" . | indent 4 }}
{{ with .Values.serviceAccount.labels }}
{{ toYaml . | indent 4 }}
{{ end }}
{{ with .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{ end }}
{{- end }}
