apiVersion: v1
kind: Service
metadata:
  name: {{ include "movement-fullnode.fullname" . }}
  labels:
{{ include "movement-fullnode.labels" . | indent 4 }}
{{ with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{ end }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ include "movement-fullnode.selectorLabels" . | indent 4 }}
  ports:
    - name: api
      port: {{ .Values.service.ports.api }}
      targetPort: {{ .Values.service.ports.api }}
      protocol: TCP
    - name: p2p
      port: {{ .Values.service.ports.p2p }}
      targetPort: {{ .Values.service.ports.p2p }}
      protocol: TCP
{{ if .Values.service.enableMetrics }}
    - name: metrics
      port: {{ .Values.service.ports.metrics }}
      targetPort: {{ .Values.service.ports.metrics }}
      protocol: TCP
{{ end }}
  sessionAffinity: None
