apiVersion: v1
kind: Service
metadata:
  name: {{ include "movement-validator.fullname" . }}
  namespace: {{ include "movement-validator.namespace" . }}
  labels:
    {{- include "movement-validator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "movement-validator.selectorLabels" . | nindent 4 }}
  ports:
  - name: api
    port: {{ .Values.service.ports.api }}
    targetPort: api
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  - name: admin
    port: {{ .Values.service.ports.admin }}
    targetPort: admin
    protocol: TCP
  - name: vfn
    port: {{ .Values.service.ports.vfn }}
    targetPort: vfn
    protocol: TCP
  - name: validator
    port: {{ .Values.service.ports.validator }}
    targetPort: validator
    protocol: TCP
  clusterIP: None  # Headless service for StatefulSet