apiVersion: v2
name: movement-validator
description: Helm chart for Movement Network validator node
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - movement
  - blockchain
  - validator
home: https://movementlabs.xyz
maintainers:
  - name: Movement Labs
    email: engineering@movementlabs.xyz