apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "movement-node.fullname" . }}-data
  labels:
{{ include "movement-node.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size | quote }}
{{ $scName := include "movement-node.storageClassName" . }}
{{ if $scName }}
  storageClassName: {{ $scName | quote }}
{{ end }}
