{{- if .Values.storage.create }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "movement-node.storageClassName" . }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  {{- range $k, $v := .Values.storage.parameters }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
